//
//  CurrencyClass.swift
//  Assignment4-Currency
//
//  Created by Ajay Shenoy on 4/16/17.
//  Copyright © 2017 Ajay Shenoy. All rights reserved.
//

import Foundation
class CurrencyClass {
    var currencyCode: [String:String]
    var fav = [[String:String]]()
    var clickedFav: [String:String]
    var currencySpace: [String:String]
    var row:Int
    init()
    {
        self.currencyCode=["EUR":"Euro",
                           "GBP":"Pound Sterling",
                           "USD":"US Dollar",
                           "KWD":"Kuwaiti Dinar",
                           "BHD":"Bahraini Dinar",
                           "JPY":"Japanese yen",
                           "AUD":"Australian Dollar",
                           "AED":"United Arab Emirates dirham",
                           "INR":"Indian Rupee",
                           "IQD":"Iraqi Dinar",
                           "NIO":"Cordoba Oro",
                           "NOK":"Norwegian Krone",
                           "NPR":"Nepalese Rupee",
                           "NZD":"New Zealand Dollar",
                           "OMR":"Rial Omani",
                           "PAB":"Balboa",
                           "PEN":"Nuevo Sol",
                           "PGK":"Kina",
                           "PHP":"Philippine Peso",
                           "PKR":"Pakistan Rupee",
                           "PLN":"Zloty",
                           "PYG":"Guarani",
                           "QAR":"Qatari Rial",
                           "RON":"Romanian New Leu",
                           "AFN":"Afghani",
                           "ALL":"Lek",
                           "AMD":"Armenian Dram",
                           "ANG":"Netherlands Antillian Guilder",
                           "AOA":"Kwanza",
                           "ARS":"Argentine Peso",
                           "AWG":"Aruban Guilder",
                           "AZN":"Azerbaijanian Manat",
                           "BAM":"Convertible Marks",
                           "BBD":"Barbados Dollar",
                           "BDT":"Bangladeshi Taka",
                           "BGN":"Bulgarian Le",
                           "BIF":"Burundian Franc",
                           "BMD":"Bermudian Dolla",
                           "BND":"Brunei Dollar",
                           "BOB":"Boliviano",
                           "BRL":"Brazilian Real",
                           "BSD":"Bahamian Dollar",
                           "BTN":"Ngultrum",
                           "BWP":"Pula",
                           "BYR":"Belarussian Ruble",
                           "BZD":"Belize Dollar",
                           "CAD":"Canadian Dollar",
                           "CDF":"Franc Congolais",
                           "CHF":"Swiss Franc",
                           "CLP":"Chilean Peso",
                           "CNY":"Yuan Renminbi",
                           "COP":"Colombian Peso",
                           "COU":"Unidad de Valor Real",
                           "CRC":"Costa Rican Colon",
                           "CUP":"Cuban Peso",
                           "CVE":"Cape Verde Escudo",
                           "CYP":"Cyprus Pound",
                           "CZK":"Czech Koruna",
                           "DJF":"Djibouti Franc",
                           "DKK":"Danish Krone",
                           "DOP":"Dominican Peso",
                           "DZD":"Algerian Dinar",
                           "EEK":"Kroon",
                           "EGP":"Egyptian Pound",
                           "ERN":"Nakfa",
                           "ETB":"Ethiopian Birr",
                           "FJD":"Fiji Dollar",
                           "FKP":"Falkland Islands Pound",
                           "GEL":"Lari",
                           "GHS":"Cedi",
                           "GIP":"Gibraltar pound",
                           "GMD":"Dalasi",
                           "GNF":"Guinea Franc",
                           "GTQ":"Quetzal",
                           "GYD":"Guyana Dollar",
                           "HKD":"Hong Kong Dollar",
                           "HNL":"Lempira",
                           "HRK":"Croatian Kuna",
                           "HTG":"Haiti Gourde",
                           "HUF":"Forint",
                           "IDR":"Rupiah",
                           "ILS":"New Israeli Shekel",
                           "IRR":"Iranian Rial",
                           "ISK":"Iceland Krona",
                           "JMD":"Jamaican Dollar",
                           "JOD":"Jordanian Dinar",
                           "KES":"Kenyan Shilling",
                           "KGS":"Som",
                           "KHR":"Riel",
                           "KMF":"Comoro Franc",
                           "KPW":"North Korean Won",
                           "KRW":"South Korean Won",
                           "KYD":"Cayman Islands Dollar",
                           "KZT":"Tenge",
                           "LAK":"Kip",
                           "LBP":"Lebanese Pound",
                           "LKR":"Sri Lanka Rupee",
                           "LRD":"Liberian Dollar",
                           "LSL":"Loti",
                           "LTL":"Lithuanian Litas",
                           "LVL":"Latvian Lats",
                           "LYD":"Libyan Dinar",
                           "MAD":"Moroccan Dirham",
                           "MDL":"Moldovan Leu",
                           "MGA":"Malagasy Ariary",
                           "MKD":"Denar",
                           "MMK":"Kyat",
                           "MNT":"Tugrik",
                           "MOP":"Pataca",
                           "MRO":"Ouguiya",
                           "MTL":"Maltese Lira",
                           "MUR":"Mauritius Rupee",
                           "MVR":"Rufiyaa",
                           "MWK":"Kwacha",
                           "MXN":"Mexican Peso",
                           "MYR":"Malaysian Ringgit",
                           "MZN":"Metical",
                           "NAD":"Namibian Dollar",
                           "NGN":"Naira",
                           "RSD":"Serbian Dinar",
                           "RUB":"Russian Ruble",
                           "RWF":"Rwanda Franc",
                           "SAR":"Saudi Riyal",
                           "SBD":"Solomon Islands Dollar",
                           "SCR":"Seychelles Rupee",
                           "SDG":"Sudanese Pound",
                           "SEK":"Swedish Krona",
                           "SGD":"Singapore Dollar",
                           "SHP":"Saint Helena Pound",
                           "SKK":"Slovak Koruna",
                           "SLL":"Leone",
                           "SOS":"Somali Shilling",
                           "SRD":"Surinam Dollar",
                           "STD":"Dobra",
                           "SYP":"Syrian Pound",
                           "SZL":"Lilangeni",
                           "THB":"Baht",
                           "TJS":"Somoni",
                           "TMM":"Manat",
                           "TND":"Tunisian Dinar",
                           "TOP":"Pa'anga",
                           "TRY":"New Turkish Lira",
                           "TTD":"Trinidad and Tobago Dollar",
                           "TWD":"New Taiwan Dollar",
                           "TZS":"Tanzanian Shilling",
                           "UAH":"Hryvnia",
                           "UGX":"Uganda Shilling",
                           "UYU":"Peso Uruguayo",
                           "UZS":"Uzbekistan Som",
                           "VEB":"Venezuelan bolívar",
                           "VND":"Vietnamese đồng",
                           "VUV":"Vatu",
                           "WST":"Samoan Tala",
                           "XAF":"CFA Franc BEAC",
                           "XCD":"East Caribbean Dollar",
                           "XPF":"CFP franc",
                           "YER":"Yemeni Rial",
                           "ZAR":"South African Rand",
                           "ZMK":"Kwacha",
                           "ZWD":"Zimbabwe Dollar"]
        self.currencySpace=["BIF":"0",
                            "CLP":"0",
                            "CVE":"0",
                            "DJF":"0",
                            "GNF":"0",
                            "ISK":"0",
                            "JPY":"0",
                            "KMF":"0",
                            "KRW":"0",
                            "RWF":"0",
                            "UGX":"0",
                            "VND":"0",
                            "VUV":"0",
                            "XAF":"0",
                            "XPF":"0",
]
        self.fav=[[String:String]]()
        self.clickedFav=[String:String]()
        self.row=0
    }
    static let CurrencyCodeValue:CurrencyClass = CurrencyClass()
    
}
